// =============================================================================
// CBSHOME API -- Auto-generated TypeScript types
// =============================================================================
//
// DO NOT EDIT THIS FILE MANUALLY.
// Generated from OpenAPI schema by backend/scripts/generate_ts_types.py
// Regenerated automatically by `cbshome update` and committed by
// cbshome-bot when the live OpenAPI schema changes.
// API version: 0.1.0
// =============================================================================

// -- Enums --------------------------------------------------------------------

/** Company profile lifecycle status. */
export type CompanyStatus = 'active' | 'hidden' | 'archived'

/** Document template kinds. Maps onto Purchase.legal_basis for the per-purchase variants; OWNERSHIP_CERTIFICATE is the live aggregate. R2 §4.3: purchase_agreement -> Purchase.legal_basis = sale gift_certificate -> Purchase.legal_basis = gift installment_subcontract -> Purchase.legal_basis = installment_tranche ownership_certificate -> live aggregate of investor's purchases for one company (no per-purchase snapshot) */
export type DocumentTemplateKind = 'purchase_agreement' | 'gift_certificate' | 'installment_subcontract' | 'ownership_certificate'

/** KYC verification status. Denormalized cache from KYCApplication. */
export type KYCStatus = 'not_started' | 'submitted' | 'approved' | 'rejected'

/** Post owner type. */
export type OwnerType = 'platform' | 'company'

/** Roadmap item surface kind (R1 §5, iter 2.4). A roadmap row carries one of three shapes; the API surface differs per kind: milestone -- traditional planned-progress-completed item with target_date. Subject to the planned -> in_progress -> completed state machine. Most existing rows fall here; migration 0033 backfills the column to this value. event -- date-bound event (target_date required, valid_until required, valid_until > target_date). Status is irrelevant; events are shown as long as today <= valid_until. announcement -- dateless message (no target_date / valid_until / status). Visible until soft-deleted. `kind` is immutable after create. To switch kind, Staff soft-deletes the row and creates a fresh one with the new kind. */
export type RoadmapItemKind = 'milestone' | 'event' | 'announcement'

/** Template lifecycle status (R2 §4.2). State machine: draft <-> active draft -> archived active -> archived When reconcile activates a new template for a (company_id, kind, lang) triple, the previous active row is automatically archived. */
export type TemplateStatus = 'draft' | 'active' | 'archived'

/** User roles in the platform. */
export type UserRole = 'investor' | 'agent' | 'company' | 'staff' | 'platform'

// -- Interfaces ---------------------------------------------------------------

/** Paginated list of agent applications. */
export interface AgentApplicationListResponse {
  items: AgentApplicationResponse[]
  total: number
}

/** Single agent application record. */
export interface AgentApplicationResponse {
  id: string
  user_id: string
  status: string
  rejection_reason?: string | null
  cooldown_until?: string | null
  reviewed_at?: string | null
  reviewed_by?: string | null
  created_at: string
}

/** Partial update of attachment metadata. Used by PATCH /staff/companies/{id}/attachments/{att_id}. Every field is optional; the service applies model_dump(exclude_unset=True) and only mutates fields that were explicitly sent. `description` accepts explicit null to clear the value. */
export interface AttachmentPatchBody {
  title?: string | null
  description?: string | null
  category?: string | null
  language?: 'en' | 'ru' | 'de' | 'ar' | null
  order?: number | null
  is_published?: boolean | null
  is_public?: boolean | null
}

/** Attachment as seen by investors / public consumers. Excludes storage_key (internal MinIO path), created_by (audit-only identity), and is_deleted (always False for these flows -- soft-deleted rows are filtered out by the service layer). */
export interface AttachmentResponse {
  id: string
  company_id: string
  category: string
  language: string
  title: string
  description: string | null
  original_filename: string
  mime_type: string
  file_size_bytes: number
  order: number
  is_published: boolean
  is_public: boolean
  created_at: string
  updated_at: string | null
}

/** Response for all auth endpoints (register, login, telegram). */
export interface AuthResponse {
  user: UserResponse
  session_token: string
}

/** Active avatar session info. */
export interface AvatarSessionResponse {
  id: string
  staff_id: string
  target_user_id: string
  status: string
  ip_address: string
  created_at: string
  ended_at?: string | null
}

/** Request to start avatar session. */
export interface AvatarStartRequest {
  target_user_id: string
}

/** Response after starting avatar session. */
export interface AvatarStartResponse {
  avatar_session_id: string
  session_token: string
}

/** Ledger balance split by status. */
export interface BalanceResponse {
  frozen: number
  confirmed: number
}

/** Request to block a user. */
export interface BlockRequest {
  reason?: string | null
}

export interface Body_create_attachment_staff_endpoint_api_v1_staff_companies__company_id__attachments_post {
  metadata: string
  file: string
}

export interface Body_replace_attachment_staff_endpoint_api_v1_staff_companies__company_id__attachments__attachment_id__replace_patch {
  file: string
}

export interface Body_set_roadmap_cover_endpoint_api_v1_staff_companies__company_id__roadmap__item_id__cover_put {
  file: string
}

/** Single commission or volume bonus entry. */
export interface CommissionEntry {
  id: string
  type: string
  amount_cents: number
  status: string
  created_at: string
  level?: number | null
  investor_name?: string | null
  product_name?: string | null
  period_type?: string | null
  rank?: number | null
}

/** Response for GET /agent/commissions/me. */
export interface CommissionListResponse {
  items: CommissionEntry[]
  total: number
}

/** Response for GET /agent/commissions/summary (Task 2b Block C). Server-side month-to-date commission aggregate -- replaces the dashboard's client-side sum over the first 100 history entries (TD-COMMISSION-MONTH-AGG). Statuses frozen+confirmed, reversed excluded; "commission:" reason prefix only (volume bonuses are a separate concept on the dashboard). */
export interface CommissionSummaryResponse {
  month_to_date_cents: number
}

/** Sales analytics for the authenticated company. Fields: total_revenue_cents: SUM(paid_cents) on active purchases (lifetime). revenue_this_month_cents: SUM(paid_cents) on active purchases with created_at >= start of current UTC month. total_options_sold: SUM(units WHERE legal_basis='sale') on active purchases (lifetime). sales_by_month: last 12 months that had at least one sale, oldest first (so the UI can render a left-to-right time axis without sorting). Empty months are skipped (no zero-padding). sales_by_product: ALL products of the company (including archived and zero-sales), sorted by revenue_cents DESC. Lets staff see what isn't selling at a glance. */
export interface CompanyAnalyticsResponse {
  total_revenue_cents: number
  revenue_this_month_cents: number
  total_options_sold: number
  sales_by_month: SalesByMonthEntry[]
  sales_by_product: SalesByProductEntry[]
}

/** Aggregated dashboard for the authenticated company. Fields: passive_balance: company's earnings ledger split by status. total_revenue_cents: SUM(Purchase.paid_cents) for active purchases of this company. Gift purchases naturally contribute 0 here. total_options_sold: SUM(Purchase.units WHERE legal_basis='sale') for active purchases. Gifts are excluded so the number reflects commercial activity, not pool consumption (pool consumption lives in pool.consumed below). products_count: COUNT(Product) for non-archived products. pool: active OptionPool snapshot, or None if the company hasn't had a pool created yet (newly created company before staff runs POST /staff/companies/{id}/pool). recent_transactions: last 20 Transaction rows for the company's user_id, newest first. */
export interface CompanyDashboardResponse {
  passive_balance: BalanceResponse
  total_revenue_cents: number
  total_options_sold: number
  products_count: number
  pool?: PoolEmbedResponse | null
  recent_transactions: CompanyTransactionResponse[]
}

/** Full company detail with roadmap items (staff). */
export interface CompanyDetailResponse {
  id: string
  user_id: string
  name: string
  description: string | null
  logo_url: string | null
  cover_url: string | null
  promo_video_url: string | null
  presentation_url: string | null
  price_per_unit_cents: number
  distribution_config: Record<string, unknown>
  total_supply: number
  shares_per_option: number
  status: string
  created_at: string
  updated_at: string | null
  roadmap?: RoadmapItemResponse[]
}

/** Paginated list of companies (staff). */
export interface CompanyListResponse {
  items: CompanyResponse[]
  total: number
  page: number
  per_page: number
}

/** Position detail for a single company with paginated purchases. */
export interface CompanyPositionDetailResponse {
  company_id: string
  company_name: string
  logo_url: string | null
  total_units: number
  sale_units: number
  gift_units: number
  total_paid_cents: number
  avg_price_cents: number
  current_price_cents: number
  current_value_cents: number
  purchases: PurchaseItemResponse[]
  total: number
  page: number
  per_page: number
}

/** Per-company position in the portfolio. */
export interface CompanyPositionResponse {
  company_id: string
  company_name: string
  logo_url: string | null
  total_units: number
  sale_units: number
  gift_units: number
  total_paid_cents: number
  avg_price_cents: number
  current_price_cents: number
  current_value_cents: number
  purchases_count: number
}

/** Company info for staff (includes distribution_config). */
export interface CompanyResponse {
  id: string
  user_id: string
  name: string
  description: string | null
  logo_url: string | null
  cover_url: string | null
  promo_video_url: string | null
  presentation_url: string | null
  price_per_unit_cents: number
  distribution_config: Record<string, unknown>
  total_supply: number
  shares_per_option: number
  status: string
  created_at: string
  updated_at: string | null
}

/** Per-company aggregate for the dashboard widget. */
export interface CompanySummaryResponse {
  company_id: string
  company_name: string
  logo_url: string | null
  total_units: number
  invested_cents: number
  current_value_cents: number
}

/** Single row of the recent transactions feed. Mirrors transactions.schemas.TransactionResponse minus user_id. from_attributes=True so the service can model_validate(orm_row) directly; missing optional fields default to None. */
export interface CompanyTransactionResponse {
  id: string
  type: string
  amount_cents: number
  currency: string
  reference_id?: string | null
  reference_type?: string | null
  details?: Record<string, unknown> | null
  created_at: string
}

/** GET /api/v1/staff/consistency -- all semaphore results. */
export interface ConsistencyResponse {
  overall_status: string
  total: number
  passed: number
  failed: number
  results: SemaphoreResult[]
}

/** Request body for creating/getting a crypto deposit address. */
export interface CreateAddressRequest {
  network: string
}

/** Create a new company with user and profile. */
export interface CreateCompanyRequest {
  email: string
  password: string
  name: string
  description?: string | null
  logo_url?: string | null
  cover_url?: string | null
  promo_video_url?: string | null
  presentation_url?: string | null
  price_per_unit_cents: number
  distribution_config: Record<string, unknown>
  total_supply: number
  shares_per_option?: number
}

/** Staff creates an event. */
export interface CreateEventRequest {
  title: string
  description?: string | null
  cover_url?: string | null
  starts_at: string
  ends_at?: string | null
  location?: string | null
  url?: string | null
  is_published?: boolean
}

/** Create an installment plan for a product. product_installment_id: which template to use. referral_link_id: optional referral (Sprint 7.2 stub). */
export interface CreateInstallmentPlanRequest {
  product_installment_id: string
  referral_link_id?: string | null
}

/** Add an installment plan template to a product. */
export interface CreateInstallmentRequest {
  name: string
  plan_config: Record<string, unknown>
}

/** Create a new active pool for a company. equity_percent: percentage of company.total_supply to allocate for sale. Must be > 0 and <= 100. The actual total_options is computed server-side as floor(company.total_supply * equity_percent / 100). */
export interface CreatePoolRequest {
  equity_percent: number | string
}

/** Staff creates a post. */
export interface CreatePostRequest {
  owner_type: 'platform' | 'company'
  owner_id?: string | null
  title: string
  body: string
  cover_url?: string | null
  tags?: string[] | null
  is_banner?: boolean
  is_published?: boolean
}

/** Create a new product for a company. */
export interface CreateProductRequest {
  company_id: string
  name: string
  description?: string | null
  package_size: number
  cover_url?: string | null
  purchase_config?: Record<string, unknown> | null
}

/** Instant purchase of a product. referral_link_id: optional referral link (Sprint 7.2). Omit for organic purchase. */
export interface CreatePurchaseRequest {
  referral_link_id?: string | null
}

/** Add a roadmap item to a company (R1 §5). `kind` defaults to MILESTONE for backward compatibility with the pre-2.4 surface. Per-kind validation is enforced by the model_validator below: milestone -- valid_until forbidden. target_date optional. status defaults to 'planned' (service layer). event -- target_date REQUIRED, valid_until REQUIRED, valid_until > target_date. announcement -- target_date / valid_until / status all forbidden. `cover_storage_key` is intentionally NOT in this body. The cover is set via the dedicated multipart endpoint PUT /staff/companies/{id}/roadmap/{item_id}/cover. Service-level checks (not visible here): - linked_product_id must belong to the same company. - post_id must reference an existing Post. */
export interface CreateRoadmapItemRequest {
  kind?: RoadmapItemKind
  title: string
  description?: string | null
  target_date?: string | null
  valid_until?: string | null
  status?: string | null
  external_url?: string | null
  post_id?: string | null
  linked_product_id?: string | null
}

/** Request to promote an existing user to staff role. */
export interface CreateStaffRequest {
  user_id: string
}

/** POST /api/v1/withdrawals -- request a withdrawal. */
export interface CreateWithdrawalRequest {
  amount_cents: number
}

/** Incoming crypto webhook payload. Stub schema -- real provider will have different fields. This captures the minimum needed to create a Payment and record an active_ledger entry. */
export interface CryptoWebhookRequest {
  network: string
  to_address: string
  from_address: string
  tx_hash: string
  amount_crypto: string
  amount_usd_cents: number
  confirmed_block?: number | null
  exchange_rate?: string
}

/** Platform-wide statistics for staff dashboard. */
export interface DashboardStatsResponse {
  total_users: number
  users_by_role: Record<string, unknown>
  pending_kyc_count: number
  active_avatar_sessions: number
}

/** Full dashboard summary for the authenticated user. */
export interface DashboardSummaryResponse {
  active_balance: BalanceResponse
  passive_balance: BalanceResponse
  total_invested_cents: number
  total_units: number
  current_value_cents: number
  companies_count: number
  companies: CompanySummaryResponse[]
}

/** Response for crypto deposit address endpoint. */
export interface DepositAddressResponse {
  address: string
  network: string
  user_id: string
}

/** Staff creates a new document. */
export interface DocumentCreateRequest {
  type: string
  language: string
  title: string
  version?: number
  required_for_roles?: string[]
}

/** Document representation in API responses. */
export interface DocumentResponse {
  id: string
  type: string
  version: number
  language: string
  title: string
  required_for_roles?: string[]
  status: string
  created_by: string
  created_at: string
  updated_at?: string | null
  is_signed?: boolean | null
}

/** Response after user signs a document. */
export interface DocumentSigningResponse {
  id: string
  document_id: string
  signed_at: string
}

/** Staff updates a document (partial update). Only provided fields are applied (exclude_unset in service). Status changes are validated against the state machine. */
export interface DocumentUpdateRequest {
  title?: string | null
  status?: string | null
  required_for_roles?: string[] | null
}

/** Investor in the agent's downline (commission-mirror levels). Level = number of agent hops from the investor up to the requesting agent: direct investors are L1, investors under a direct sub-agent are L2, one agent deeper -- L3. L4+ are outside the 3-level commission area and excluded. display_name is MASKED (decision #5): no email, phone or KYC status is ever exposed, uniformly across all levels. */
export interface DownlineInvestorEntry {
  user_id: string
  display_name: string
  level: number
  registered_at: string
  purchase_volume_cents: number
}

/** Sub-agent in the agent's downline, agent-hop depth 1..3. recruited_investor_count / direct_volume_cents cover only the sub-agent's DIRECT investors (decision #4, non-recursive). own_purchase_volume_cents is the sub-agent's OWN purchases (decision #8): agents are buyers too, and their purchases feed the requesting agent's commission exactly like investor purchases -- without this field the screen would show less volume than the agent is actually commissioned on. */
export interface DownlineSubAgentEntry {
  user_id: string
  display_name: string
  level: number
  registered_at: string
  recruited_investor_count: number
  direct_volume_cents: number
  own_purchase_volume_cents: number
}

/** POST /api/v1/auth/email/login -- request body. */
export interface EmailLoginRequest {
  email: string
  password: string
}

/** POST /api/v1/auth/email/register -- request body. */
export interface EmailRegisterRequest {
  email: string
  password: string
  referral_code?: string | null
}

/** Paginated event list. */
export interface EventListResponse {
  items: EventResponse[]
  total: number
  page: number
  per_page: number
}

/** Single event. */
export interface EventResponse {
  id: string
  title: string
  description?: string | null
  cover_url?: string | null
  starts_at: string
  ends_at?: string | null
  location?: string | null
  url?: string | null
  is_published: boolean
  created_by: string
  created_at: string
  updated_at?: string | null
}

/** Installment plan with tranches (for detail endpoint). */
export interface InstallmentPlanDetailResponse {
  id: string
  investor_id: string
  product_id: string
  company_id: string
  product_installment_id: string
  total_price_cents: number
  total_units: number
  price_per_unit_cents: number
  status: string
  created_at: string
  completed_at: string | null
  defaulted_at: string | null
  tranches?: InstallmentTrancheResponse[]
}

/** Paginated list of installment plans. */
export interface InstallmentPlanListResponse {
  items: InstallmentPlanResponse[]
  total: number
  page: number
  per_page: number
}

/** Installment plan summary (for list endpoint). */
export interface InstallmentPlanResponse {
  id: string
  investor_id: string
  product_id: string
  company_id: string
  product_installment_id: string
  total_price_cents: number
  total_units: number
  price_per_unit_cents: number
  status: string
  created_at: string
  completed_at: string | null
  defaulted_at: string | null
}

/** Staff inputs for the installment calculator (Sprint 4.3 B4). Set membership for num_tranches and amount_rounding_cents is enforced inside calculator.py so we get a clean BadRequestError message; Pydantic does not natively validate membership in a frozenset without a custom validator. last_tranche_percent uses Field bounds (Pydantic understands ge/le) so the 422 path catches obviously bad inputs before the calculator runs. */
export interface InstallmentPreviewRequest {
  num_tranches: number
  last_tranche_percent: number
  amount_rounding_cents: number
}

/** Calculator output: ready-to-submit plan_config + summary. plan_config is the same shape consumed by POST /staff/products/{id}/installments -- staff can edit bonus_units / agent_bonus_units in the UI, then submit unchanged. */
export interface InstallmentPreviewResponse {
  plan_config: Record<string, unknown>
  summary: InstallmentPreviewSummary
}

/** Flat human-friendly numbers for the staff UI (Sprint 4.3 B4). Derived from plan_config; here so the UI does not have to traverse the tranches list to show key headline numbers (regular vs last tranche amount/options, total). */
export interface InstallmentPreviewSummary {
  total_amount_cents: number
  package_size: number
  num_tranches: number
  regular_amount_cents: number
  last_amount_cents: number
  regular_units: number
  last_units: number
  regular_units_percent: number
  last_units_percent: number
}

/** Installment plan template. */
export interface InstallmentResponse {
  id: string
  product_id: string
  name: string
  plan_config: Record<string, unknown>
  created_at: string
}

/** Single tranche within an installment plan. */
export interface InstallmentTrancheResponse {
  id: string
  plan_id: string
  number: number
  due_date: string
  amount_cents: number
  units_unlocked: number
  status: string
  paid_at: string | null
  purchase_id: string | null
}

/** Compact KYCApplication row for the user detail history. Mirrors the columns the staff detail modal actually renders: id (for action endpoints), status (badge color), created_at (timeline ordering / submission date), updated_at (when the status changed for terminal statuses). Distinct from KYCQueueItem -- that one carries denormalized user info for the global queue, this one is already nested inside a per-user response so user_id / email / name would duplicate the parent. */
export interface KYCApplicationSummary {
  id: string
  status: string
  created_at: string
  updated_at?: string | null
}

/** Pending KYC application with basic user info. */
export interface KYCQueueItem {
  id: string
  user_id: string
  status: string
  created_at: string
  email?: string | null
  first_name?: string | null
  last_name?: string | null
}

/** Request body for KYC rejection with optional reason. */
export interface KYCRejectRequest {
  reason?: string | null
}

/** Current KYC status for the authenticated user. */
export interface KYCStatusResponse {
  kyc_status: string
  application_id?: string | null
  application_status?: string | null
}

/** Response after submitting a KYC application. */
export interface KYCSubmitResponse {
  id: string
  status: string
  created_at: string
}

/** Webhook payload from KYC provider (stub). In production, this will be replaced with SumSub webhook format and signature validation. Current stub accepts user_id + status. */
export interface KYCWebhookRequest {
  user_id: string
  status: string
}

/** Single agent entry in the leaderboard. */
export interface LeaderboardEntry {
  agent_id: string
  agent_name: string
  rank: number
  volume_cents: number
  is_me?: boolean
}

/** Response for GET /agent/leaderboard. */
export interface LeaderboardResponse {
  entries: LeaderboardEntry[]
  snapshot_at?: string | null
  period_start: string
}

/** Single delivery with parent notification data. */
export interface NotificationDeliveryResponse {
  id: string
  channel: string
  status: string
  read_at?: string | null
  sent_at?: string | null
  created_at: string
  type: string
  title: string
  body: string
  action_data?: Record<string, unknown> | null
  priority: number
}

/** Paginated list of deliveries. */
export interface NotificationListResponse {
  items: NotificationDeliveryResponse[]
  total: number
  page: number
  per_page: number
}

/** Paginated payment history response. */
export interface PaymentHistoryResponse {
  items: PaymentResponse[]
  total: number
  page: number
  per_page: number
}

/** Individual payment in history listing. */
export interface PaymentResponse {
  id: string
  amount_cents: number
  currency: string
  payment_type: string
  provider: string
  status: string
  frozen_until?: string | null
  created_at: string
  updated_at?: string | null
}

/** Response for GET /api/v1/users/me/payout-details. */
export interface PayoutDetailsResponse {
  payout_details?: Record<string, unknown> | null
}

/** Pool snapshot embedded in the dashboard payload. Unlike pools.schemas.PoolResponse, this does not include id or company_id -- the dashboard caller already knows whose company this is. status is included so the UI can disable pool-edit actions on a future archived pool without a second call. */
export interface PoolEmbedResponse {
  total_options: number
  equity_percent: string
  consumed: number
  remaining: number
  status: string
}

/** Pool info with computed consumption and remaining options. consumed and remaining are NOT columns on OptionPool -- they are aggregated at request time from active Purchase rows of the same company. Service layer fills them. Sprint 4.4: consumed and remaining are required fields (no defaults). The router always calls with_consumed_remaining() before validating into this schema; a missing populate would be a server bug. */
export interface PoolResponse {
  id: string
  company_id: string
  equity_percent: string
  total_options: number
  status: string
  created_at: string
  updated_at: string | null
  consumed: number
  remaining: number
}

/** Full portfolio: list of company positions. */
export interface PortfolioResponse {
  positions: CompanyPositionResponse[]
}

/** Paginated post list. */
export interface PostListResponse {
  items: PostResponse[]
  total: number
  page: number
  per_page: number
}

/** Single post with dismiss status. */
export interface PostResponse {
  id: string
  owner_type: string
  owner_id?: string | null
  title: string
  body: string
  cover_url?: string | null
  tags?: string[] | null
  is_banner: boolean
  is_published: boolean
  published_at?: string | null
  created_by: string
  created_at: string
  updated_at?: string | null
  is_dismissed?: boolean
}

/** Embedded Post preview inside a roadmap item (R1 §5). Built by the companies service layer from a Post row -- never via `from_attributes` because `excerpt` is derived (first 200 chars of body, plain text). Kept here in companies/schemas (rather than posts/schemas) because the consumer is the roadmap response and importing across modules is allowed in one direction only by the existing project convention. */
export interface PostSnippetResponse {
  id: string
  title: string
  cover_url?: string | null
  excerpt: string
}

/** Paginated price-history list (iter 2.6c B3). Wraps PriceHistoryResponse with the same pagination envelope used by CompanyListResponse and every other staff list endpoint, so the frontend table component can drive both list flows with one pagination contract. */
export interface PriceHistoryListResponse {
  items: PriceHistoryResponse[]
  total: number
  page: number
  per_page: number
}

/** Single price change record. */
export interface PriceHistoryResponse {
  id: string
  price_per_unit_cents: number
  changed_at: string
  changed_by: string
}

/** Product info for staff view. */
export interface ProductResponse {
  id: string
  company_id: string
  pool_id: string
  name: string
  description: string | null
  package_size: number
  cover_url: string | null
  purchase_config: Record<string, unknown> | null
  price_per_unit_cents: number
  status: string
  created_at: string
  updated_at: string | null
}

/** Public company detail with stats and roadmap items. iter 2.4 R1 §1.6.2: `stats` is REQUIRED -- the storefront detail surface always shows pool / growth numbers, populated by the router from get_public_company_stats. Roadmap items carry the R1 §5 extension (kind, cover_url, post snippet, ...). */
export interface PublicCompanyDetailResponse {
  id: string
  name: string
  description: string | null
  logo_url: string | null
  cover_url: string | null
  promo_video_url: string | null
  presentation_url: string | null
  price_per_unit_cents: number
  total_supply: number
  shares_per_option: number
  status: string
  created_at: string
  stats: PublicCompanyStatsResponse
  roadmap?: RoadmapItemResponse[]
}

/** Paginated list of companies (public). */
export interface PublicCompanyListResponse {
  items: PublicCompanyResponse[]
  total: number
  page: number
  per_page: number
}

/** Company info for public storefront (no distribution_config). */
export interface PublicCompanyResponse {
  id: string
  name: string
  description: string | null
  logo_url: string | null
  cover_url: string | null
  promo_video_url: string | null
  presentation_url: string | null
  price_per_unit_cents: number
  total_supply: number
  shares_per_option: number
  status: string
  created_at: string
}

/** Aggregated storefront stats for a company (iter 2.4 R1 §1.6.2). Pool numbers come from the company's single active OptionPool; a company without an active pool reports zeros (it's a fresh "start-state" company that has not yet had a pool issued, which is a rare but legal rendering case rather than a 404). `price_growth_90d_percent` uses the "stretched window" semantics (R1 §1.6.2 decision): the baseline price is the latest CompanyPriceHistory row older than 90 days; for companies whose full history is shorter than 90 days, the baseline falls back to the earliest history row. No history rows at all -> growth = 0. Integer-rounded percent (no decimals). */
export interface PublicCompanyStatsResponse {
  pool_total_options: number
  options_sold: number
  options_sold_percent: number
  price_growth_90d_percent: number
}

/** Public product detail with installment plans. Sprint 4.4: installments is required (no `= []` default). Backend always returns an array; the optional-by-default trip through OpenAPI was forcing `?? []` on the frontend. Router populates explicitly, even if empty. */
export interface PublicProductDetailResponse {
  id: string
  company_id: string
  name: string
  description: string | null
  package_size: number
  price_per_unit_cents: number
  price_per_pack_cents: number
  cover_url?: string | null
  available_packages: number
  company_name: string
  company_logo_url?: string | null
  company_cover_url?: string | null
  installments: InstallmentResponse[]
}

/** Paginated list of products (public). */
export interface PublicProductListResponse {
  items: PublicProductResponse[]
  total: number
  page: number
  per_page: number
}

/** Product info for public storefront. company_name / company_logo_url / company_cover_url are denormalised from CompanyProfile by the public router (Sprint F4.1) so the storefront can render a card without a second API call. Sprint 4.3: package_size (renamed from units), available_packages (renamed from sold_units, now COMPUTED from the pool, not from purchase counts). pool_id is intentionally NOT exposed here -- it is a staff-side identifier. Sprint 4.4: price_per_pack_cents added; available_packages is now required (no `= 0` default). Both are populated by the public router; missing populate is a server bug, not a soft fallback. */
export interface PublicProductResponse {
  id: string
  company_id: string
  name: string
  description: string | null
  package_size: number
  price_per_unit_cents: number
  price_per_pack_cents: number
  cover_url?: string | null
  available_packages: number
  company_name: string
  company_logo_url?: string | null
  company_cover_url?: string | null
}

/** Single purchase record in the position detail. */
export interface PurchaseItemResponse {
  id: string
  product_id: string
  legal_basis: string
  units: number
  paid_cents: number
  price_per_unit_cents: number
  status: string
  created_at: string
}

/** Single purchase record. */
export interface PurchaseResponse {
  id: string
  investor_id: string
  product_id: string
  company_id: string
  legal_basis: string
  units: number
  paid_cents: number
  price_per_unit_cents: number
  status: string
  created_at: string
}

/** Manual purchase reversal result summary (R-2.2 Block B). */
export interface PurchaseReversalResponse {
  purchase_id: string
  total_reversed_cents: number
  active_entries_reversed: number
  passive_entries_reversed: number
  units_returned: number
  affected_user_ids: string[]
}

/** Result of mark-all-read operation. */
export interface ReadAllResponse {
  marked: number
}

/** Public referral-click payload (Task 1 Block B). max_length mirrors ReferralLink.code String(20); min_length=1 rejects empty strings at the framework edge instead of spending a no-op UPDATE (STYLE-44-01). Fire-and-forget: the endpoint replies 204 whether or not the code matches a link. */
export interface ReferralClickRequest {
  code: string
}

/** Response for GET /referrals/downline/me (two collections, decision #1 -- not a polymorphic flat tree). */
export interface ReferralDownlineResponse {
  investors: DownlineInvestorEntry[]
  sub_agents: DownlineSubAgentEntry[]
}

/** Paginated list of referral links. */
export interface ReferralLinkListResponse {
  items: ReferralLinkResponse[]
  total: number
  page: number
  per_page: number
}

/** Single referral link with per-link funnel counters (Task 1 D). click_count is the raw counter column; registration_count and purchase_count are aggregates computed in get_my_links via two batched GROUP BY queries (never per-link queries). */
export interface ReferralLinkResponse {
  id: string
  agent_id: string
  code: string
  is_active: boolean
  click_count: number
  registration_count: number
  purchase_count: number
  created_at: string
}

/** Agent referral statistics (funnel order: links -> clicks -> registrations -> purchases -> commission). */
export interface ReferralStatsResponse {
  total_links: number
  total_clicks: number
  total_registrations: number
  total_purchases: number
  total_commission_cents: number
}

/** Body for rejecting an agent application. */
export interface RejectRequest {
  reason: string
}

/** POST /api/v1/staff/withdrawals/{id}/reject -- reject with reason. */
export interface RejectWithdrawalRequest {
  reason: string
}

/** Bulk reorder of attachments inside one (company_id, category) scope (iter 2.6c B5). `item_ids` must be the COMPLETE list of every non-deleted attachment for the given (company_id, category) -- the service enforces an exact set match. Sending a partial list is a 400, as is sending an unknown id; either case suggests the staff UI is out of sync with the database and a silent reorder would scramble the visible order for everyone else. Mirrors the shape of ReorderRoadmapRequest for consistency, with the addition of `category` -- attachment order is scoped to (company_id, category) rather than per-company. */
export interface ReorderAttachmentsRequest {
  category: string
  item_ids: string[]
}

/** Reorder roadmap items by providing ordered list of IDs. */
export interface ReorderRoadmapRequest {
  item_ids: string[]
}

/** Reversal result summary. */
export interface ReversalResponse {
  payment_id: string
  total_reversed_cents: number
  active_entries_reversed: number
  passive_entries_reversed: number
  purchases_reversed: number
  tranches_unwound?: Record<string, unknown>[]
  affected_user_ids: string[]
}

/** Request body for payment reversal (chargeback). */
export interface ReversePaymentRequest {
  reason?: string | null
}

/** Single roadmap item (R1 §5 extension). `cover_url` is a presigned URL generated by the service layer from `cover_storage_key` (None when no cover uploaded). `post` is populated when the row has a `post_id` -- the companies service does a LEFT JOIN on posts in get_company_detail so this avoids N+1. */
export interface RoadmapItemResponse {
  id: string
  kind: string
  title: string
  description: string | null
  target_date: string | null
  valid_until?: string | null
  status: string
  order: number
  external_url?: string | null
  post_id?: string | null
  linked_product_id?: string | null
  cover_url?: string | null
  post?: PostSnippetResponse | null
  created_at: string
  updated_at: string | null
}

/** One bucket of sales_by_month. month: 'YYYY-MM' (UTC, derived from Purchase.created_at). */
export interface SalesByMonthEntry {
  month: string
  revenue_cents: number
  options_sold: number
}

/** One row of sales_by_product. revenue_cents and options_sold are zero for products that exist but have no active sales. Archived products are included too -- the point of this list is to show which products do not sell. */
export interface SalesByProductEntry {
  product_id: string
  product_name: string
  revenue_cents: number
  options_sold: number
}

/** POST /api/v1/users/me/select-role -- onboarding role selection. */
export interface SelectRoleRequest {
  role: string
}

/** Result of a single consistency semaphore check. */
export interface SemaphoreResult {
  name: string
  status: string
  severity: string
  details?: Record<string, unknown> | null
}

/** Attachment as seen by staff: includes operational fields hidden from auth/public flows. The model column is `created_by` (UUID NOT NULL today, FK ondelete=RESTRICT); we expose it as `created_by_id` at the API boundary for naming clarity and type it as Optional to leave room for a future ondelete=SET NULL. `validation_alias="created_by"` lets Pydantic populate this field from the ORM attribute without renaming the column. */
export interface StaffAttachmentResponse {
  id: string
  company_id: string
  category: string
  language: string
  title: string
  description: string | null
  original_filename: string
  mime_type: string
  file_size_bytes: number
  order: number
  is_published: boolean
  is_public: boolean
  created_at: string
  updated_at: string | null
  storage_key: string
  is_deleted: boolean
  created_by_id?: string | null
}

/** Paginated payment list for staff. */
export interface StaffPaymentListResponse {
  items: StaffPaymentResponse[]
  total: number
  page: number
  per_page: number
}

/** Payment with user_id for staff views. */
export interface StaffPaymentResponse {
  id: string
  amount_cents: number
  currency: string
  payment_type: string
  provider: string
  status: string
  frozen_until?: string | null
  created_at: string
  updated_at?: string | null
  user_id: string
}

/** Staff profile response. */
export interface StaffProfileResponse {
  id: string
  user_id: string
  permissions: Record<string, unknown>
  is_active: boolean
  created_at: string
}

/** Request body for manual purchase reversal (R-2.2 Block B). */
export interface StaffReversePurchaseRequest {
  reason?: string | null
}

/** POST /api/v1/auth/telegram -- request body. */
export interface TelegramAuthRequest {
  init_data: string
  referral_code?: string | null
}

/** Single template with full body for staff inspection (R2 §4.5). Adds: - html_content: utf-8 decoded body of <storage_prefix>/template.html fetched from MinIO at request time. Read-through the Redis HTML cache (R2 §4.10) so the staff inspect flow shares cache warmth with the renderer. - storage_prefix: the MinIO folder path for this template. Useful when staff wants to jump into MinIO Web UI to see the asset files alongside the parsed HTML. */
export interface TemplateDetailResponse {
  id: string
  company_id: string | null
  kind: string
  language: string
  version: number
  title: string
  status: string
  asset_files: string[]
  created_by: string | null
  created_at: string
  updated_at: string | null
  storage_prefix: string
  html_content: string
  is_platform_default: boolean
}

/** Template as seen by staff in the list view (R2 §4.5). Excludes html_content and storage_prefix to keep list payloads small; use TemplateDetailResponse for the per-template inspection endpoint that includes the full HTML body. `is_platform_default` is a computed flag: True for the platform fallback rows (company_id IS NULL), False for per-company overrides. Pydantic recomputes it from company_id on every serialisation, so the flag cannot drift away from the row. */
export interface TemplateResponse {
  id: string
  company_id: string | null
  kind: string
  language: string
  version: number
  title: string
  status: string
  asset_files: string[]
  created_by: string | null
  created_at: string
  updated_at: string | null
  is_platform_default: boolean
}

/** GET /api/v1/transactions -- paginated event log. */
export interface TransactionListResponse {
  items: TransactionResponse[]
  total: number
  page: number
  per_page: number
}

/** Single transaction event in API responses. */
export interface TransactionResponse {
  id: string
  user_id: string
  type: string
  amount_cents: number
  currency: string
  reference_id?: string | null
  reference_type?: string | null
  details?: Record<string, unknown> | null
  created_at: string
}

/** Badge counter for unread deliveries. */
export interface UnreadCountResponse {
  count: number
}

/** Partial update of company profile. Only provided fields are updated. distribution_config triggers financial_operations permission check in router. Sprint 4.3: total_supply and shares_per_option are NOT in this schema. Pool size changes happen via PATCH /staff/companies/{id}/pool, and a shares_per_option change is a split (future scope). */
export interface UpdateCompanyRequest {
  name?: string | null
  description?: string | null
  logo_url?: string | null
  cover_url?: string | null
  promo_video_url?: string | null
  presentation_url?: string | null
  distribution_config?: Record<string, unknown> | null
  status?: string | null
}

/** Staff partial update of an event (PATCH). */
export interface UpdateEventRequest {
  title?: string | null
  description?: string | null
  cover_url?: string | null
  starts_at?: string | null
  ends_at?: string | null
  location?: string | null
  url?: string | null
  is_published?: boolean | null
}

/** Update an installment plan template. */
export interface UpdateInstallmentRequest {
  name?: string | null
  plan_config?: Record<string, unknown> | null
}

/** PUT /api/v1/users/me/payout-details -- set withdrawal payment methods. Free-form JSONB. Validation of specific methods (crypto, IBAN, etc.) will be added in future sprints when payment provider is integrated. */
export interface UpdatePayoutDetailsRequest {
  payout_details: Record<string, unknown>
}

/** Request to update staff permissions (partial update). Only provided keys are updated; missing keys retain current values. */
export interface UpdatePermissionsRequest {
  avatar_mode?: boolean | null
  kyc_approve?: boolean | null
  payment_review?: boolean | null
  user_block?: boolean | null
  financial_operations?: boolean | null
  agent_application_review?: boolean | null
  translation_edit?: boolean | null
  company_manage?: boolean | null
  content_manage?: boolean | null
}

/** Update an existing active pool's total_options (допэмиссия). total_options: new absolute number of options in the pool. Must be > 0 and <= company.total_supply (validated in service). The service rejects values below already-consumed options. equity_percent is recomputed by the service based on the new total_options. Callers do not pass it. */
export interface UpdatePoolRequest {
  total_options: number
}

/** Staff partial update of a post (PATCH). */
export interface UpdatePostRequest {
  title?: string | null
  body?: string | null
  cover_url?: string | null
  tags?: string[] | null
  is_banner?: boolean | null
  is_published?: boolean | null
}

/** Change company share price (cascades to products). */
export interface UpdatePriceRequest {
  price_per_unit_cents: number
}

/** Partial update of product. purchase_config triggers financial_operations permission check in router. Sprint 4.3: package_size, company_id and pool_id are immutable. Not in update schema. */
export interface UpdateProductRequest {
  name?: string | null
  description?: string | null
  cover_url?: string | null
  purchase_config?: Record<string, unknown> | null
}

/** Change product status. */
export interface UpdateProductStatusRequest {
  status: string
}

/** Partial update of a roadmap item (R1 §5). `kind` is intentionally OMITTED -- it is immutable after create. To change kind, Staff soft-deletes the item and creates a new one. Per-kind invariants from CreateRoadmapItemRequest are NOT re-checked here (we don't know the current kind without a DB read at validation time). The service layer re-applies the relevant rules using the persisted kind before committing. `cover_storage_key` is not in the body for the same reason as the create schema -- a dedicated multipart endpoint manages it. */
export interface UpdateRoadmapItemRequest {
  title?: string | null
  description?: string | null
  target_date?: string | null
  valid_until?: string | null
  status?: string | null
  external_url?: string | null
  post_id?: string | null
  linked_product_id?: string | null
}

/** Full user detail for staff view. iter 2.7 A5 additions (kyc-in-detail extension): - latest_application_id : newest KYCApplication.id or None. - latest_application_status : its status, mirroring user.kyc_status for non-trivial cases (and None for users who have never submitted). - kyc_applications_history : up to KYC_HISTORY_LIMIT newest rows, NEWEST FIRST. Empty list if the user has never submitted. */
export interface UserDetailResponse {
  id: string
  role: string
  is_active: boolean
  onboarding_step: string
  kyc_status: string
  profile: Record<string, unknown>
  language: string
  created_at: string
  updated_at?: string | null
  email?: string | null
  staff_profile?: StaffProfileResponse | null
  latest_application_id: string | null
  latest_application_status: string | null
  kyc_applications_history: KYCApplicationSummary[]
}

/** Unified user list item -- any role, optional staff_profile. */
export interface UserListItem {
  id: string
  role: string
  is_active: boolean
  kyc_status: string
  email?: string | null
  first_name?: string | null
  last_name?: string | null
  created_at: string
  staff_profile?: StaffProfileResponse | null
}

/** Paginated user list. */
export interface UserListResponse {
  items: UserListItem[]
  total: number
  page: number
  per_page: number
}

/** User representation in API responses. Excludes credentials (sensitive: password hashes, tokens). Profile is returned as-is from JSONB. Email is extracted from credentials via User.email property. iter 2.6c B6: `staff_profile` is populated by the service layer when `role == "staff"` -- it carries the staff profile id, is_active flag, and the EFFECTIVE permission matrix (defaults merged with per-staff overrides). For non-staff users the field is null. The frontend Staff Platform tab keys off this field to gate the whole surface. */
export interface UserResponse {
  id: string
  role: string
  email?: string | null
  is_active: boolean
  onboarding_step: string
  kyc_status: string
  profile: Record<string, unknown>
  payout_details?: Record<string, unknown> | null
  language: string
  created_at: string
  updated_at?: string | null
  staff_profile?: StaffProfileResponse | null
}

/** PATCH /api/v1/users/me -- updatable profile fields. All fields are optional. Only provided fields are updated (exclude_unset in service layer). profile: merged with existing JSONB via set_jsonb(). language: direct assignment. NOT NULL in DB -- explicit null is rejected in service layer, not here (avoids conflict with Pydantic default=None for "not sent" semantics). */
export interface UserUpdate {
  profile?: Record<string, unknown> | null
  language?: string | null
}

/** POST /api/v1/auth/verify-email -- request body. */
export interface VerifyEmailRequest {
  code: string
}

/** GET /api/v1/withdrawals/me -- paginated list. */
export interface WithdrawalListResponse {
  items: WithdrawalResponse[]
  total: number
}

/** Single withdrawal in API responses. */
export interface WithdrawalResponse {
  id: string
  user_id: string
  amount_cents: number
  status: string
  payout_details_snapshot: Record<string, unknown>
  rejection_reason?: string | null
  created_at: string
  confirmed_at?: string | null
  processing_at?: string | null
  completed_at?: string | null
  rejected_at?: string | null
  failed_at?: string | null
}
