"""crypto_invoices replaces crypto_addresses

ONE REVISION FOR BOTH HALVES, ON PURPOSE. Dropping the old table and
creating the new one is a single transition: a deployment stopped
between two revisions would have a product that can neither resolve an
old-style deposit nor record a new-style invoice, and there is no
sensible thing for it to do in that state.

NO DATA MIGRATION, AND THE REASON IS CHECKABLE RATHER THAN ASSUMED.
crypto_addresses only ever held strings of the form AIVIS_<network>_<hex>
generated by a stub. Those are not addresses on any chain: no wallet
would accept one as a destination, so no transfer can ever have been
sent to one and no row can correspond to money. Nothing is carried
forward because there is nothing that could be.

Revision ID: 0047_crypto_invoices
Revises: 0046_retire_native_notifications
Create Date: 2026-08-28
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0047_crypto_invoices"
down_revision: str | None = "0046_retire_native_notifications"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "crypto_invoices",
        sa.Column("id", sa.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            sa.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        # NOT NULL: the row is written only once the service has issued
        # the invoice, so there is no state in which this is unknown.
        sa.Column("service_invoice_id", sa.UUID(as_uuid=True), nullable=False),
        sa.Column("network", sa.String(32), nullable=False),
        sa.Column("address", sa.String(255), nullable=False),
        sa.Column("invoice_amount_cents", sa.BigInteger(), nullable=False),
        # Cache of the service's status. No CHECK constraint listing the
        # six values: the vocabulary belongs to the service, and a copy
        # of it welded into a database constraint would turn a status
        # the service adds later into a failing INSERT here.
        sa.Column("status", sa.String(32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )

    # UNIQUE rather than a plain index: one service invoice maps to one
    # local row. Two rows pointing at the same invoice would let one
    # incoming event resolve to two users.
    op.create_index(
        "uq_crypto_invoices_service_invoice_id",
        "crypto_invoices",
        ["service_invoice_id"],
        unique=True,
    )
    op.create_index(
        "ix_crypto_invoices_user_id",
        "crypto_invoices",
        ["user_id"],
    )
    # Serves the open-invoice lookup, which filters on both columns.
    op.create_index(
        "ix_crypto_invoices_user_network",
        "crypto_invoices",
        ["user_id", "network"],
    )

    op.drop_table("crypto_addresses")


def downgrade() -> None:
    # Recreated exactly as migration 0007 built it, including the unique
    # index name the removed service code used to recognise its own
    # IntegrityError. A downgrade that produced a subtly different table
    # would leave a database that passes inspection and fails at runtime.
    op.create_table(
        "crypto_addresses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("network", sa.String(20), nullable=False),
        sa.Column("address", sa.String(255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_crypto_addresses_user_network",
        "crypto_addresses",
        ["user_id", "network"],
        unique=True,
    )

    op.drop_index("ix_crypto_invoices_user_network", table_name="crypto_invoices")
    op.drop_index("ix_crypto_invoices_user_id", table_name="crypto_invoices")
    op.drop_index(
        "uq_crypto_invoices_service_invoice_id", table_name="crypto_invoices"
    )
    op.drop_table("crypto_invoices")
