# =============================================================================
# CBSHOME Backend -- Application Configuration
# =============================================================================
#
# APP_VERSION: single source of truth for API version.
#   Used in FastAPI app init and GET / response.
#
# All settings loaded from environment variables (or .env file).
# Pydantic-settings validates types and applies defaults automatically.
#
# APP_ENV (R51, fail-closed):
#   REQUIRED, no default. An unset or empty APP_ENV refuses to start
#   the application -- the pre-R51 default of "development" silently
#   enabled the entire dev profile (CORS *, dev webhook secrets, dev
#   DB fallback) on any host missing its .env. The empty-string
#   sentinel below exists only so the validator can raise a readable
#   error instead of pydantic's bare "Field required".
#   Anything other than "development" is treated as production-grade.
# =============================================================================

from pydantic import model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

# Single source of truth for API version.
# Import as: from app.core.config import APP_VERSION, settings
APP_VERSION = "0.1.0"

# Valid structlog log levels.
_VALID_LOG_LEVELS = {"DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"}


class Settings(BaseSettings):
    """Application settings loaded from environment variables."""

    # -- Application --
    # R51: empty sentinel, NOT a default -- the validator rejects it
    # first thing (see APP_ENV note in the module header).
    app_env: str = ""
    log_level: str = "INFO"
    cors_origins: str = "*"

    # -- Database --
    database_url: str = ""

    # -- Redis --
    redis_url: str = "redis://localhost:6379/0"

    # -- MinIO (S3-compatible object storage, Refactor 2 iter 2.1) --
    # Backend uses the service account credentials (ACCESS_KEY/SECRET_KEY),
    # NOT the root credentials. Root creds live in .env only because
    # docker-compose and minio-init need them at bootstrap. They are not
    # mapped here -- the BaseSettings extra="ignore" silently drops them.
    minio_endpoint: str = ""
    minio_access_key: str = ""
    minio_secret_key: str = ""
    minio_bucket: str = "aivis-attachments"
    minio_region: str = "us-east-1"
    # Presigned URL TTL: short for authenticated download, long for public.
    minio_presigned_ttl_auth: int = 900       # 15 minutes
    minio_presigned_ttl_public: int = 86400   # 24 hours
    # Hard limit on uploaded file size. Mirrored in nginx client_max_body_size.
    # Files larger than this are rejected at ingress; backend trusts the
    # ingress because Staff-driven upload happens exclusively via MinIO Web
    # UI (see Refactor 2 §3.7), not through the API.
    minio_max_file_size_mb: int = 100

    # -- Auth --
    secret_key: str = ""
    session_ttl_days: int = 30
    max_concurrent_sessions: int = 5

    # -- Telegram --
    telegram_bot_token: str = "TEST"

    # -- Telegram Auth Security --
    auth_rate_limit_max_requests: int = 5
    auth_rate_limit_window_seconds: int = 60
    auth_init_data_ttl_seconds: int = 300
    auth_clock_skew_seconds: int = 60

    # -- KYC (SumSub) --
    sumsub_api_key: str = "TEST"
    sumsub_secret_key: str = "TEST"

    # -- KYC Webhook --
    # Shared secret for webhook authentication (stub).
    # In production, replace with SumSub signature validation.
    kyc_webhook_secret: str = ""

    # -- Email (SMTP primary, Mailgun fallback) --
    smtp_host: str = "host.docker.internal"
    smtp_port: int = 25
    smtp_user: str = ""
    smtp_password: str = ""
    smtp_from_email: str = "noreply@mail.cbshome.org"
    smtp_use_tls: bool = False
    mailgun_api_key: str = "TEST"
    mailgun_domain: str = "mail.cbshome.org"
    # CBSHOME runs in EU; production .env (generated by install_cbshome.sh)
    # and .env.example both default to the EU endpoint. Override to
    # https://api.mailgun.net only for a US-region Mailgun account.
    mailgun_api_url: str = "https://api.eu.mailgun.net"
    high_secured_domains: str = ""

    # -- Crypto payments --
    crypto_networks: str = "TRC20,ERC20,BEP20,PoS"
    freezing_hours_crypto: int = 1
    freezing_hours_bank: int = 72 * 14

    # -- Crypto Webhook (Sprint 5.2) --
    # Shared secret for blockchain webhook authentication (stub).
    # In production, replace with provider-specific signature validation.
    crypto_webhook_secret: str = ""

    # -- Payment confirmation daemon (Sprint 5.3) --
    confirmation_worker_interval_minutes: int = 5

    # -- Installments --
    installment_default_days: int = 7
    installment_worker_hour: int = 3

    # -- Withdrawals (Sprint 6.3) --
    min_withdrawal_cents: int = 1000       # $10.00
    max_withdrawal_cents: int = 10000000   # $100,000.00

    # -- Agent --
    agent_application_cooldown_days: int = 30

    # -- Referral click rate limit (Task 1 Block B) --
    # Per-IP anti-abuse limit for POST /api/v1/public/referral-click.
    # This is NOT click deduplication: click_count is a raw counter by
    # design; the limit only caps how fast one IP can inflate it.
    referral_click_rate_limit_max_requests: int = 60
    referral_click_rate_limit_window_seconds: int = 60

    # -- Social proof cache --
    social_proof_cache_ttl: int = 300

    # -- Notifications (Sprint 8.1) --
    notification_max_delivery_attempts: int = 3
    notification_worker_interval_minutes: int = 1

    # -- Volume Bonuses (Sprint 7.3) --
    # Basis points: 200 = 2.00%, 100 = 1.00%.
    volume_bonus_monthly_bp: int = 200
    volume_bonus_quarterly_bp: int = 100
    leaderboard_top_monthly: int = 20
    leaderboard_top_quarterly: int = 10
    leaderboard_worker_interval_minutes: int = 60

    # -- Events (iter 2.7b) --
    # Ceiling for GET /api/v1/events/upcoming?limit=N. The dashboard
    # widget asks for 3; this bounds an over-large client request so the
    # query stays cheap. Clamped in posts/service.py::list_upcoming_events
    # (an oversized limit degrades to this value, not a 422).
    events_upcoming_max_limit: int = 50

    # -- Computed properties --

    @property
    def is_dev(self) -> bool:
        """True when running in development mode."""
        return self.app_env == "development"

    @property
    def crypto_network_list(self) -> list[str]:
        """Parsed list of crypto networks from comma-separated string."""
        return [n.strip() for n in self.crypto_networks.split(",") if n.strip()]

    @property
    def high_secured_domain_list(self) -> list[str]:
        """Parsed list of high-secured email domains (Mailgun-only delivery)."""
        return [d.strip().lower() for d in self.high_secured_domains.split(",") if d.strip()]

    @property
    def minio_max_file_size_bytes(self) -> int:
        """Hard upload limit converted to bytes."""
        return self.minio_max_file_size_mb * 1024 * 1024

    @model_validator(mode="after")
    def _validate(self) -> "Settings":
        """Apply dev defaults and enforce production requirements."""
        # -- APP_ENV is REQUIRED (R51, fail-closed) -- checked FIRST so
        # a missing value produces this message and not a cascade of
        # production-requirement errors.
        env = self.app_env.strip().lower()
        if not env:
            raise ValueError(
                "APP_ENV is required and has no default (fail-closed). "
                "Set APP_ENV=development for a dev box or "
                "APP_ENV=production for a deployment. Anything other "
                "than 'development' is treated as production-grade."
            )
        self.app_env = env
        is_dev = env == "development"

        # -- log_level --
        if self.log_level.upper() not in _VALID_LOG_LEVELS:
            raise ValueError(
                f"Invalid LOG_LEVEL: {self.log_level}. "
                f"Valid: {', '.join(sorted(_VALID_LOG_LEVELS))}"
            )
        self.log_level = self.log_level.upper()

        # -- CORS in production --
        if not is_dev and self.cors_origins.strip() == "*":
            raise ValueError(
                "CORS_ORIGINS=* is not allowed in production. "
                "Set explicit origins, e.g. https://cbshome.org"
            )

        # -- database_url --
        if not self.database_url:
            if is_dev:
                self.database_url = (
                    "postgresql+asyncpg://aivis:aivis@localhost:5432/aivis"
                )
            else:
                raise ValueError("DATABASE_URL is required in production.")

        # -- secret_key --
        if not self.secret_key:
            if is_dev:
                self.secret_key = (
                    "dev-only-insecure-key-do-not-use-in-production"
                )
            else:
                raise ValueError(
                    "SECRET_KEY is required in production. "
                    "Generate with: python -c "
                    "\"import secrets; print(secrets.token_urlsafe(64))\""
                )

        # -- kyc_webhook_secret --
        if not self.kyc_webhook_secret:
            if is_dev:
                self.kyc_webhook_secret = "dev-webhook-secret"
            else:
                raise ValueError(
                    "KYC_WEBHOOK_SECRET is required in production."
                )

        # -- crypto_webhook_secret (Sprint 5.2) --
        if not self.crypto_webhook_secret:
            if is_dev:
                self.crypto_webhook_secret = "dev-crypto-webhook-secret"
            else:
                raise ValueError(
                    "CRYPTO_WEBHOOK_SECRET is required in production."
                )

        # -- telegram_bot_token --
        if self.telegram_bot_token in ("", "TEST"):
            if not is_dev:
                raise ValueError(
                    "TELEGRAM_BOT_TOKEN must be set to a real token "
                    "in production (not 'TEST')."
                )

        # -- MinIO credentials (Refactor 2 iter 2.1) --
        # Required at runtime in any environment because the storage
        # abstraction is in the hot path of attachments / templates /
        # roadmap covers. Dev-only fallbacks would silently mask a
        # broken docker-compose stack.
        if not self.minio_endpoint:
            if is_dev:
                self.minio_endpoint = "http://localhost:9000"
            else:
                raise ValueError("MINIO_ENDPOINT is required in production.")

        if not self.minio_access_key:
            if is_dev:
                self.minio_access_key = "minioadmin"
            else:
                raise ValueError("MINIO_ACCESS_KEY is required in production.")

        if not self.minio_secret_key:
            if is_dev:
                self.minio_secret_key = "minioadmin"
            else:
                raise ValueError("MINIO_SECRET_KEY is required in production.")

        return self

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )


settings = Settings()
