# =============================================================================
# AIVIS.ONE Backend -- Symmetric Crypto Helpers (TASK-38, 2FA)
# =============================================================================
#
# encrypt_secret() / decrypt_secret() -- encryption AT REST for the TOTP
# secret (app/modules/users/service.py's setup_totp/confirm_totp_setup
# write the encrypted form; app/modules/auth/service.py's
# verify_totp_or_backup_code reads it back to compute a live code).
#
# WHY ENCRYPTION, NOT HASHING. A TOTP secret has to be usable to COMPUTE
# a fresh 6-digit code on every login -- unlike a password
# (hash_password/verify_password in auth/service.py, one-way argon2),
# it cannot be one-way hashed. It has to be recoverable, so it is
# encrypted instead: reversible, but not plaintext in `credentials`
# JSONB, where a raw DB dump would otherwise defeat 2FA for every user
# in one query. Backup codes are the opposite case -- used once,
# compared, never re-displayed -- and ARE hashed, via the same
# hash_password/verify_password argon2 wrappers everything else in this
# codebase uses (see users/service.py's confirm_totp_setup).
#
# WHY FERNET. `cryptography.fernet.Fernet` is this library's own
# batteries-included symmetric scheme: AES-128-CBC + HMAC-SHA256
# (encrypt-then-MAC, authenticated -- a tampered or corrupted token
# fails to decrypt rather than silently returning garbage), a
# versioned token format, and IV/nonce generation handled internally.
# Rolling AES directly would mean re-deriving all of that by hand for
# no benefit.
#
# KEY DERIVATION. settings.secret_key (app/core/config.py) already
# exists -- auto-generated in dev, REQUIRED in production -- and before
# this file had ZERO uses anywhere in this app (grep confirmed). It is
# exactly the kind of long-lived, ops-managed secret Fernet needs a key
# from, so the Fernet key is DERIVED from it via HKDF-SHA256 rather
# than introducing a second secret to provision, rotate, and document:
#   - Fernet requires a 32-byte key, base64url-encoded. secret_key is an
#     arbitrary-length string with no guaranteed byte length -- HKDF
#     turns it into exactly 32 bytes, deterministically, every time.
#   - `info=b"aivis-totp-secret-v1"` is HKDF's domain-separation label,
#     fixed and versioned. Any FUTURE derived-key use of secret_key
#     (unrelated to 2FA) would get its own distinct info label and
#     therefore a completely different key from the same root secret --
#     and a hypothetical v2 of THIS derivation could be introduced
#     later without silently reusing v1 key material for a different
#     purpose.
#   - No salt: HKDF's salt exists to defend against reuse of the SAME
#     low-entropy input (e.g. a human password) across unrelated
#     derivations. secret_key is already a high-entropy, single-purpose
#     secret (64+ bytes of urlsafe randomness when generated by the
#     command config.py's own error message recommends), so a salt adds
#     no defense here -- the fixed `info` label is what keeps this
#     derivation unambiguous.
#
# CACHING. Deriving a key is one HKDF pass -- cheap, but not free, and
# the result never changes for a given secret_key (it is read once at
# process start and never reloaded). Derived once at first use and
# cached at module scope instead of recomputed on every
# encrypt_secret/decrypt_secret call.
# =============================================================================

import base64

from cryptography.fernet import Fernet, InvalidToken
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.hkdf import HKDF

from app.core.config import settings

__all__ = ["InvalidToken", "decrypt_secret", "encrypt_secret"]

_HKDF_INFO = b"aivis-totp-secret-v1"

_fernet_instance: Fernet | None = None


def _get_fernet() -> Fernet:
    """Derive (once) and cache the Fernet instance keyed off settings.secret_key.

    Module-scope cache: settings.secret_key is read once at process
    start (pydantic-settings loads it at import time) and never changes
    for the life of the process, so there is nothing to invalidate.
    """
    global _fernet_instance
    if _fernet_instance is None:
        hkdf = HKDF(
            algorithm=hashes.SHA256(),
            length=32,
            salt=None,
            info=_HKDF_INFO,
        )
        derived = hkdf.derive(settings.secret_key.encode())
        key = base64.urlsafe_b64encode(derived)
        _fernet_instance = Fernet(key)
    return _fernet_instance


def encrypt_secret(plaintext: str) -> str:
    """Encrypt a plaintext string (the TOTP secret) for storage at rest.

    Returns the Fernet token as a str -- safe to store directly in a
    JSONB column (credentials.totp_pending.secret_encrypted /
    credentials.totp.secret_encrypted).
    """
    token = _get_fernet().encrypt(plaintext.encode())
    return token.decode()


def decrypt_secret(ciphertext: str) -> str:
    """Decrypt a Fernet token produced by encrypt_secret().

    Raises:
        cryptography.fernet.InvalidToken: the token is malformed,
            tampered with, or was encrypted under a different
            secret_key (e.g. after an undocumented key rotation with no
            migration). Deliberately NOT caught/remapped here -- every
            caller (auth/service.py's verify_totp_or_backup_code) is
            already inside a broader "does this code verify" check
            where any failure to recover the secret means "no", so the
            exception is caught at that call site instead of papered
            over in this shared helper.
    """
    return _get_fernet().decrypt(ciphertext.encode()).decode()
